version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - type: bind
        source: ./pgdata
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    image: "redis:alpine"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - redis
  migration:
    image: idoctor_web
    command: python manage.py migrate --noinput
    volumes: 
      - .:/code
    depends_on:
      - db
      - redis
  superuser:
    image: idoctor_web
    command: python manage.py createsuperuser
    volumes:
      - .:/code
    depends_on:
      - web